services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=petcommerce'
      - 'POSTGRES_DB=petcommerce'
      - 'POSTGRES_PASSWORD=petcommerce'
    volumes:
      - './volumes/petcommerce/postgres:/var/lib/postgresql/data'
